M48
; DRILL file {KiCad (7.0.0)} date Tue Sep 26 09:32:40 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-09-26T09:32:40+13:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.500
%
G90
G05
T1
X153.45Y-89.165
T2
X149.1Y-93.815
X152.9Y-93.815
T0
M30
